import { useEffect, useState } from "react";
import { Typography, Box, CircularProgress, Alert, Card } from "@mui/material";
import { alpha } from "@mui/material/styles";
import HistoryRoundedIcon from "@mui/icons-material/HistoryRounded";

import { getHistory } from "../services/api";

import HistoryTable from "../components/HistoryTable";

export default function History() {

  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    load();
  }, []);

  async function load() {
    try {
      setLoading(true);
      const res = await getHistory();
      setHistory(res.data);
    } catch (err) {
      console.log(err);
      setError("Unable to load report history.");
    } finally {
      setLoading(false);
    }
  }

  const isEmpty = !loading && !error && history.length === 0;

  return (
    <>
      <Box sx={{ display: "flex", alignItems: "flex-start", gap: 2, mb: 4 }}>

        <Box
          sx={(theme) => ({
            width: 44,
            height: 44,
            borderRadius: "12px",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            bgcolor: alpha(theme.palette.primary.main, 0.1),
            color: "primary.main",
            flexShrink: 0
          })}
        >
          <HistoryRoundedIcon fontSize="small" />
        </Box>

        <Box>
          <Typography variant="h4">History</Typography>
          <Typography variant="body2" color="text.secondary" mt={0.5}>
            Browse every report generated by CloudGuard.
          </Typography>
        </Box>

      </Box>

      {error && (
        <Alert severity="error" sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}

      <Card sx={{ p: loading || isEmpty ? 3 : 0 }}>

        {loading && (
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
              gap: 2,
              py: 10
            }}
          >
            <CircularProgress size={36} thickness={4} color="primary" />
            <Typography color="text.secondary" fontWeight={500}>
              Loading history…
            </Typography>
          </Box>
        )}

        {isEmpty && (
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
              gap: 1,
              py: 8
            }}
          >
            <HistoryRoundedIcon sx={{ fontSize: 40 }} color="disabled" />
            <Typography fontWeight={600} color="text.primary">
              No reports yet
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Upload a dataset to see it show up here.
            </Typography>
          </Box>
        )}

        {!loading && !error && history.length > 0 && (
          <HistoryTable history={history} />
        )}

      </Card>
    </>
  );

}